# Generated by Django 5.2.7 on 2025-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_monster_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='experience_reward',
        ),
        migrations.AddField(
            model_name='monster',
            name='min_experience_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=50),
        ),
    ]
