# Generated by Django 5.2.7 on 2025-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_monster_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
    ]
